config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  #root "welcome#home"
  root 'pages#home'
  #get "/pages/home", to: "pages#home"
  get "about", to: "pages#about"

  resources :articles
  get 'signup', to: "users#new"
  #post 'users', to: "users#create"
  resources :users, except: [:new]
  get 'login', to: 'sessions#new'
  post 'login', to: 'sessions#create'
  get 'logout', to: 'sessions#destroy' 

  resources :categories , exept: [:destroy]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/article.rb
class Article < ApplicationRecord
    belongs_to :user 
    has_many :article_categories
    has_many :categories, through: :article_categories
    validates :title, presence: true, length: {minimum:3, maximum:50}
    validates :description, presence: true, length: {minimum:5, maximum:300}

end

app/models/article_category.rb
class ArticleCategory < ApplicationRecord
    belongs_to :article 
    belongs_to :category 

end

app/models/category.rb
class Category < ApplicationRecord 
    validates :name, presence:true , length: {minimum: 3, maximum: 25}
    validates_uniqueness_of :name
    has_many :article_categories
    has_many :articles, through: :article_categories
end

app/models/user.rb
class User < ApplicationRecord
    before_save { self.email = email.downcase }
    has_many :articles, dependent: :destroy 
    validates :username, presence: true, uniqueness: {case_sensitive: false} , length: {minimum: 3, maximum: 25} 
    
    VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-]+(\.[a-z\d\-]+)*\.[a-z]+\z/i

    validates :email, presence: true, uniqueness: {case_sensitive: false} , length: {maximum: 105} , format: { with: VALID_EMAIL_REGEX }

    has_secure_password
    
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base

    helper_method :current_user, :logged_in?

    def current_user
        @current_user ||=  User.find(session[:user_id]) if session[:user_id]
    end
    def logged_in?
        !!current_user
    end
    def require_user
        if !logged_in? 
            flash[:alert] =" You must login in to perform that action"
            redirect_to login_path
        end
    end
    

end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
    before_action :set_article, only: [:show, :edit, :update, :destroy]
    before_action :require_user , except: [:show, :index]
    before_action :require_same_user, only: [:edit, :update, :destroy]

    def index 
        @articles = Article.paginate(page: params[:page], per_page: 4)
    end
    
    def new
        @article = Article.new
    end

    def edit 
        #@article = Article.find(params[:id])
    end

    def create
        #render plain: params[:article].inspect
        @article = Article.new(article_params)
        @article.user = current_user
        if @article.save 
            flash[:notice] = "Article was successfully created"
            redirect_to (@article)
        else 
            render 'new'
        end
    end

    def update 
        #@article=Article.find(params[:id])
        if @article.update(article_params)
            flash[:notice] = "Article was Successfully updated"
            redirect_to (@article)
        else 
            render 'edit'
        end
    end

    def show
        #@article = Article.find(params[:id])
    end
    
    def destroy 
        #@article = Article.find(params[:id])
        @article.destroy 
        flash[:notice] = "Article was successfully deleted"
        redirect_to articles_path    
    end
    private
        def article_params
            params.require(:article).permit(:title, :description, category_ids:[])
        end

        def set_article
            @article = Article.find(params[:id])
        end
        def require_same_user 
            if current_user != @article.user && !current_user.admin?
                flash[:alert] =" You can delete or update your own record"
                redirect_to @article 
            end
        end


end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController 

    before_action :require_admin, except: [:index, :show]
    def new 
        @category = Category.new
    end

    def create 
        @category = Category.new(category_params)
        if @category.save 
            flash[:notice] = "Category was successfully created"
            redirect_to @category

        else
            render 'new'
        end
    end

    def show 
        @category = Category.find(params[:id])
        @articles = @category.articles.paginate(page: params[:page],per_page: 5)
    end

    def index
        @categories=Category.all 
    end

    def edit 
        @category = Category.find(params[:id])
    end
    def update 
        @category = Category.find(params[:id])
        if @category.update(category_params)
            flash[:notice] ="Category name updated successfully"
            redirect_to @category
        else
            render 'edit'
        end
    end
    private 
        def category_params
            params.require(:category).permit(:name)
        end
        def require_admin
            if !(logged_in? && current_user.admin?)
                flash[:alert] ="Only admins can perform that action"
                redirect_to categories_path
            end
        end

end

app/controllers/pages_controller.rb
class PagesController < ApplicationController   
    def home
        #redirect_to articles_path if logged_in?    
    end

    def about

    end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
    def new 
    end

    def create 
        user= User.find_by(email: params[:session][:email].downcase)
        if user && user.authenticate(params[:session][:password])
            session[:user_id] = user.id 
            flash[:notice] = "Logged in successfully"
            redirect_to user 
        
        else
            flash.now[:alert] = "Login not successful"
            render 'new'
        end
    end

    def destroy 
        session[:user_id] = nil
        flash[:notice]= "Logged out"
        redirect_to root_path
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController 
    before_action :set_user, only: [:show, :edit, :update, :destroy]
    before_action :require_user, only: [:edit, :update]
    before_action :require_same_user, only: [:edit, :update, :destroy]
    def new 
        @user = User.new
    end
    def create 
        @user=User.new(user_params)
        if @user.save 
            session[:user_id]= @user.id 
            flash[:notice]= "Welcome to the assign #{@user.username}, you have successfully signed up"
            redirect_to articles_path 
        else   
            render 'new'
        end
    end
    def show 
        #@user=User.find(params[:id])
        @articles=@user.articles.paginate(page: params[:page], per_page: 3)
    end
    def index 
        @users = User.paginate(page: params[:page], per_page: 3)
    end
    def edit 
        #@user=User.find(params[:id])
    end

    def update 
        #@user=User.find(params[:id])
        if @user.update(user_params)
            flash[:notice] = "Your info updated successfully"
            redirect_to @user
        else  
            render 'edit'
        end 
    end
    def destroy 
        @user.destroy 
        session[:user_id] = nil if @user == current_user
        flash[:notice] = "Account and all deleted"
        redirect_to articles_path
    end

    private
        def user_params 
            params.require(:user).permit(:username, :email, :password)
        end
        def set_user
            @user=User.find(params[:id])
        end
        def require_same_user
            if current_user != @user && !current_user.admin? 
                flash[:alert] = "You can only edit your own account"
                redirect_to @user 
            end
        end

end

app/helpers/application_helper.rb
module ApplicationHelper
    def gravatar_for(user,options ={size:80})
        email_address = user.email.downcase
        hash = Digest::MD5.hexdigest(email_address)
        size = options[:size]
        gravatar_url = "https://www.gravatar.com/avatar/#{hash}?s=#{size}"
        image_tag(gravatar_url,alt: user.username)
    end


end

app/views/articles/_article.html.erb
<table>
    <tr>
        <th> Title </th>
        <th> Description </th>
    </tr>
    <% @articles.each do |article| %>
    <tr>
        <td> <%= article.title %> </td>
        <td> <%= article.description %> </td>
        <% if logged_in? && ( article.user == current_user  || current_user.admin?) %>
        <td> <%= link_to "Edit", edit_article_path(article) %> </td>
        <% end %>
        <td> <%= link_to "Show", article_path(article) %> </td>
        <% if logged_in? && ( article.user == current_user  || current_user.admin?) %>
        <td> <%= button_to "Delete", article_path(article), method: :delete,form:{ data: {turbo_confirm: "Are you sure?"} } %> </td>
        <% end %>
        <% if article.user %>
           <td> by <%= link_to article.user.username+" ", user_path(article.user) %> </td>
        <% end %>
        <% if article.categories.any? %> 
         <td> tags: <%= render article.categories %> </td>
         <% end %>
    </tr>
    <% end %>
</table>

app/views/articles/_form.html.erb
<% if @article.errors.any? %>
<h2> The following validations prevented the article from creating</h2>
<ul>
    <% @article.errors.full_messages.each do |msg| %>
    <li> <%= msg %> </li>
    <% end %>
</ul>
<% end %>

<%= form_for @article do |f| %>
    <p>
        <%= f.label :title%> <br>
        <%= f.text_field :title %>
    </p>
    <p>
        <%= f.label :description%><br/>
        <%= f.text_area :description %>
    </p>
     <p>
        <%= f.label :category %><br/>
        <%= f.collection_select(:category_ids, Category.all, :id, :name, {prompt: "Select"},{multiple:true}) %>
    </p>
    <p>
        <%= f.submit %>
    </p>

<%end%>
<%= link_to "Back to articles listing", articles_path %>

app/views/articles/edit.html.erb
<h1> edit existing  article</h1>
<%= link_to 'Logout', logout_path , data: { "turbo-method": :delete} %>
<%= render 'form' %>

app/views/articles/index.html.erb
<center>
    <h1> Listing all Articles </h1>
    <p> <%= link_to "Create new article", new_article_path %> </p>
    <%= will_paginate @articles %>
    <%= render 'article' %>

    <%= link_to "Home" , root_path %>
    <%= link_to 'Logout', logout_path , data: { "turbo-method": :delete} %>

 %>
</center>

app/views/articles/new.html.erb
<center>
    <h1> Create an article </h1>
    <%= link_to 'Logout', logout_path , data: { "turbo-method": :delete} %>
    <%= render 'form' %>
</center>

app/views/articles/show.html.erb
<h1> Showing selected article</h1>
<%= link_to 'Logout', logout_path , data: { "turbo-method": :delete} %>
<p> Title: <%= @article.title %> </p>
<p> Description: <%= @article.description %> </p>
<p> by <%= @article.user.username if @article.user %> </p>
   <% if @article.categories.any? %> 
   <p>Category tags: <%= render @article.categories %> </p>
   <% end %>
 <% if logged_in? && ( @article.user == current_user || current_user.admin?) %>
<p>  <%= link_to "Edit", edit_article_path(@article) %> </p>
<% end %>
<%= link_to "Back to articles listing",articles_path %>

app/views/categories/_category.html.erb
<%= link_to category.name+" , " , category_path(category) %>

app/views/categories/_form.html.erb
<% if @category.errors.any? %>
    <h2 class="alert" > The following errors prevented the user from creating</h2>
    <ul class ="alert-heading">
    <% @category.errors.full_messages.each do |msg| %>
    <li> <%= msg %> </li>
    <% end %>
    </ul>
    <% end %>
    <%= form_for @category do |f| %>
    <p>
    <%= f.label :name, "Category name" %> <br>
    <%= f.text_field :name %>
    </p>
    <p>
    <%= f.submit %>
    </p>

<%end%> 

app/views/categories/edit.html.erb
<center>
    <h1>Edit Category name</h1>
    <%= render 'form' %>
    <%= link_to "Back to home", root_path %> | 
    <%= link_to 'Logout', logout_path , data: { "turbo-method": :delete} %>
</center>

app/views/categories/index.html.erb
<center>
    <h1> Listing all Categories </h1>
    <table>
    <tr>
        <th> Name </th>
        <th> Count of articles </th>
    </tr>
    <% @categories.each do |category| %>
    <tr>
        <td> <%=  link_to category.name, category_path(category) %> </td>
        <td> <%= pluralize(+category.articles.count,"article") %> </td>
    </tr>
    <% end %>
</table>
</center>

app/views/categories/new.html.erb
<center>
    <h1>Create a new category</h1>

    <% if @category.errors.any? %>
    <h2 class="alert" > The following errors prevented the user from creating</h2>
    <ul class ="alert-heading">
    <% @category.errors.full_messages.each do |msg| %>
    <li> <%= msg %> </li>
    <% end %>
    </ul>
    <% end %>

    <%= form_for @category do |f| %>
    <p>
    <%= f.label :name, "Category name" %> <br>
    <%= f.text_field :name %>
    </p>
    <p>
    <%= f.submit %>
    </p>

    <%end%> 
    <%= link_to "Back to home", root_path %> | 
    <%= link_to 'Logout', logout_path , data: { "turbo-method": :delete} %>
</center>

app/views/categories/show.html.erb
<center>
    <h1> Category: <%= @category.name %> </h1>

     <% if logged_in? && current_user.admin? %>
    <%= link_to "Edit category name", edit_category_path(@category) %> <br>
    <% end %>
    <%= link_to "Back to home", root_path %> <br> 
    <%= link_to 'Logout', logout_path , data: { "turbo-method": :delete} %>
    <%= will_paginate @articles %>
    <%= render 'articles/article' %>
</center>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Assign Blog</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
  
  <% flash.each do |name,msg|  %>
    <ul>
      <li> <%= msg %> </li>
    </ul>
  <% end%>
<%= yield %>

</body>
</html>

app/views/pages/about.html.erb
<h1> Welcome to about page </h1>

<%= link_to 'Home', root_path  %>

app/views/pages/home.html.erb
<center>
    <h1> Welcome to home page </h1>
    <%= link_to 'About', about_path  %> | 
    <%= link_to 'Articles', articles_path %> |
    <%= link_to 'Bloggers' ,users_path %> |
    <%= link_to 'Signup', signup_path %> |
    <% if logged_in? %>
    <%= link_to 'Logout', logout_path %>
    <% else %>
    <%= link_to 'Login', login_path %> 
    <% end %>
</center>

app/views/users/_form.html.erb
<% if @user.errors.any? %>
<h2> The following validations prevented the user from creating</h2>
<ul>
    <% @user.errors.full_messages.each do |msg| %>
    <li> <%= msg %> </li>
    <% end %>
</ul>
<% end %>

<%= form_for @user do |f| %>
    <p>
        <%= f.label :username %> <br>
        <%= f.text_field :username %>
    </p>
    <p>
        <%= f.label :email %><br/>
        <%= f.email_field :email %>
    </p>
    <p>
        <%= f.label :password %><br/>
        <%= f.password_field :password %>
    </p>
    <p>
        <%= f.submit(@user.new_record? ? "Sign up" : "Update account") %>
    </p>

<%end%>

app/views/users/edit.html.erb
<h1>Edit your profile</h1>

<%= render 'form' %>

<%= link_to "Back to home", root_path %> |
<%= link_to 'Logout', logout_path , data: { "turbo-method": :delete} %>

app/views/users/index.html.erb
<center>
    <h1> Display Users</h1>
    <%= link_to 'Home', root_path  %> |
    <%= link_to 'Logout', logout_path , data: { "turbo-method": :delete} %> <br>
    <%= will_paginate @users %>
    <table>
    <tr>
        <th> Title </th>
        <th> Description </th>
    </tr>
    <% @users.each do |user| %>
    <tr>
        <td> <%= link_to user.username, (user) %> </td>
        <td> <%= link_to gravatar_for(user,size:150), user %> </td>
        <td> <%= pluralize(user.articles.count,"article") %> </td>
         <% if logged_in? &&  user == current_user  %>
        <td> <%= link_to "Edit Profile", edit_user_path(user) %> </td>
        <% end %>
         <% if logged_in? &&  current_user.admin? %>
         <td> <%= button_to "Delete user", user_path(user), method: :delete %> </td>
          <%end%>
        <td> <%= link_to "View Profile", user %> </td>
        <td> Joined <%= time_ago_in_words(user.created_at) %> </td>
    </tr>
    <% end %>
</table>
</center>

app/views/users/new.html.erb
<h1>Sign up</h1>

<%= render 'form' %>

<%= link_to "Back to home", root_path %> | 
<%= link_to 'Logout', logout_path , data: { "turbo-method": :delete} %>

app/views/users/show.html.erb
<center>

    <h1><%= @user.username %> Profile </h1>
    <%= gravatar_for @user ,size:200 %> <br>
     <% if logged_in? && @user == current_user %>
    <%= link_to "Edit your profile", edit_user_path(@user) %> <br>
    <%= button_to "Delete your profile", user_path(current_user), method: :delete %>
    <% end %>
    <%= link_to "Back to home", root_path %> <br> |
    <%= link_to 'Logout', logout_path , data: { "turbo-method": :delete} %>
    <%= will_paginate @articles %>
    <%= render 'articles/article' %>

</center>